### ISSUE TITLE
Getting a “question mark” fail when uploading (iOS, Safari

### ISSUE THREAD

**Issue by Chrisatsinnoh** [check-face/facemorph.me#19]
While testing FaceMorph on iOS to generate unique faces for drawing reference reasons, it was working fine until I ran into this problem today. Whenever I upload an image, it gives me a question mark error; and thus, FaceMorph is unable to proceed in both video and slider formats as a result of the broken upload. It works fine when I do not use the upload method to morph new images, however. But I think the uploading has broken down on Safari, in an iPhone.

![IMG_1352](https://github.com/check-face/facemorph.me/assets/28026341/b1755d1e-2c57-447a-822d-78eb705c3052)

**Comment by olivercoad** [comment]
Hey, thanks for opening the issue. Just tried it and it seems like
generating anything new at all doesn't work, not just encoding from uploads.

Looking at the metrics, the issue is the server has run out of disk space.
I'll fix it when I get home and setup an alert in grafana to warn us early
if it happens again.

**Comment by olivercoad** [comment]
@cdilga I had to delete the snapshots to release some disk space, but made a new one
